#ifndef TARJETA
#define TARJETA

#define TIPO_VISA "VISA"
#define TIPO_AMEX "AMEX"
#define TIPO_NARA "NARA"

#define COEF_VISA 0.6
#define COEF_AMEX 0.3
#define COEF_NARA 0.5

#define EXCEPTIONAL_RATE_VISA 25
#define EXCEPTIONAL_RATE_AMEX 10
#define EXCEPTIONAL_RATE_NARA 20

#endif